/**
 * 07 · Penrose — P3 rhomb tiling by inflation
 *
 * Penrose's P3 tiling uses two rhombs — thin (36° / 144°) and fat
 * (72° / 108°) — with matching rules that prohibit any periodic completion.
 * Equivalently, both rhombs can be bisected into Robinson triangles (kind 0
 * = thin Robinson, kind 1 = fat Robinson) and the tiling is generated by
 * the inflation (substitution) rule:
 *
 *   thin  → 1 thin  + 1 fat
 *   fat   → 2 fat   + 1 thin
 *
 * Start with a "sun" of ten thin triangles around the origin, recurse six
 * levels of the inflation rule, and color tiles pseudo-randomly. The palette
 * is Islamic-tile-inspired; Lu & Steinhardt (2007) identified the quasi-
 * crystalline geometry at the 15th-century Darb-i Imam shrine in Isfahan.
 *
 * References
 * - R. Penrose, "The role of aesthetics in pure and applied mathematical
 *   research," Bulletin of the Institute of Mathematics and its Applications
 *   10, 266–271 (1974).
 * - N. G. de Bruijn, "Algebraic theory of Penrose's non-periodic tilings,"
 *   Nederl. Akad. Wetensch. Proc. Ser. A 84, 39–66 (1981) — the
 *   cut-and-project construction.
 * - P. J. Lu & P. J. Steinhardt, "Decagonal and Quasi-Crystalline Tilings in
 *   Medieval Islamic Architecture," Science 315, 1106–1110 (2007).
 *
 * @module renderers/penrose
 */

import { addGrain, mulberry32, type Renderer } from "../shared";

type TriPt = { x: number; y: number };
type Tri = { kind: 0 | 1; A: TriPt; B: TriPt; C: TriPt };

// Four Islamic-tile palette families. Each entry: [bgLight, bgDark, fat[], thin[]].
// Palette 0 is the original turquoise/lapis/ochre scheme.
const PALETTES = [
  {
    bgLight: "#f0e3c4",
    bgDark: "#d6c69e",
    fat: ["#3a7882", "#7a4d2e", "#d4a55a", "#274059"],
    thin: ["#bf6745", "#c79350", "#7f8d7f", "#3a4e62"],
  },
  {
    bgLight: "#e8ddd0",
    bgDark: "#c9b89a",
    fat: ["#8b3a3a", "#c47a2a", "#e8c56a", "#5a2020"],
    thin: ["#d4804a", "#b05828", "#7a6040", "#3a2018"],
  },
  {
    bgLight: "#d8e4e0",
    bgDark: "#a8c0b8",
    fat: ["#2a5c4a", "#1a3c5a", "#4a8870", "#8ab0a0"],
    thin: ["#3a7060", "#285070", "#5a9878", "#a0c8b8"],
  },
  {
    bgLight: "#e8e0f0",
    bgDark: "#c0aed8",
    fat: ["#4a2860", "#8a3878", "#c870a0", "#6a2048"],
    thin: ["#784898", "#a058a8", "#d890c0", "#5a1840"],
  },
];

export const renderPenrose: Renderer = (ctx, W, H, SEED) => {
  const r = mulberry32(SEED);
  const pal = PALETTES[(SEED >>> 0) % PALETTES.length];
  // Rotate the initial sun so each slug shows a different orientation of the tiling.
  const sunRotation = r() * Math.PI * 2;

  const bg = ctx.createRadialGradient(W / 2, H / 2, 0, W / 2, H / 2, W * 0.8);
  bg.addColorStop(0, pal.bgLight);
  bg.addColorStop(1, pal.bgDark);
  ctx.fillStyle = bg;
  ctx.fillRect(0, 0, W, H);

  const phi = (1 + Math.sqrt(5)) / 2;

  function subdivide(triangles: Tri[]): Tri[] {
    const result: Tri[] = [];
    for (const t of triangles) {
      const A = t.A;
      const B = t.B;
      const C = t.C;
      if (t.kind === 0) {
        // Thin Robinson triangle → 1 thin + 1 fat.
        const P = {
          x: A.x + (B.x - A.x) / phi,
          y: A.y + (B.y - A.y) / phi,
        };
        result.push({ kind: 0, A: C, B: P, C: B });
        result.push({ kind: 1, A: P, B: C, C: A });
      } else {
        // Fat Robinson triangle → 2 fat + 1 thin.
        const Q = {
          x: B.x + (A.x - B.x) / phi,
          y: B.y + (A.y - B.y) / phi,
        };
        const R = {
          x: B.x + (C.x - B.x) / phi,
          y: B.y + (C.y - B.y) / phi,
        };
        result.push({ kind: 1, A: R, B: C, C: A });
        result.push({ kind: 1, A: Q, B: R, C: B });
        result.push({ kind: 0, A: R, B: Q, C: A });
      }
    }
    return result;
  }

  // Initial "sun" — ten fat triangles in a wheel around the origin.
  const cx = W / 2;
  const cy = H / 2 + 30;
  const R = 520;
  let triangles: Tri[] = [];
  for (let i = 0; i < 10; i++) {
    const a1 = ((i * 2 - 1) * Math.PI) / 10 + sunRotation;
    const a2 = ((i * 2 + 1) * Math.PI) / 10 + sunRotation;
    const A = { x: cx, y: cy };
    const B = { x: cx + R * Math.cos(a1), y: cy + R * Math.sin(a1) };
    const C = { x: cx + R * Math.cos(a2), y: cy + R * Math.sin(a2) };
    if (i % 2 === 0) {
      triangles.push({ kind: 0, A: A, B: B, C: C });
    } else {
      triangles.push({ kind: 0, A: A, B: C, C: B });
    }
  }

  for (let n = 0; n < 6; n++) triangles = subdivide(triangles);

  let pIdx = 0;
  for (const t of triangles) {
    const color =
      t.kind === 0
        ? pal.fat[pIdx++ % pal.fat.length]
        : pal.thin[pIdx++ % pal.thin.length];
    ctx.fillStyle = color;
    ctx.beginPath();
    ctx.moveTo(t.A.x, t.A.y);
    ctx.lineTo(t.B.x, t.B.y);
    ctx.lineTo(t.C.x, t.C.y);
    ctx.closePath();
    ctx.fill();
  }

  // Grout — slim outlines on the long sides only, so the short sides
  // (the matching-rule edges) remain visually invisible.
  ctx.strokeStyle = "rgba(20, 14, 8, 0.55)";
  ctx.lineWidth = 0.6;
  for (const t of triangles) {
    ctx.beginPath();
    ctx.moveTo(t.B.x, t.B.y);
    ctx.lineTo(t.A.x, t.A.y);
    ctx.moveTo(t.B.x, t.B.y);
    ctx.lineTo(t.C.x, t.C.y);
    ctx.stroke();
  }

  const vg = ctx.createRadialGradient(
    W / 2,
    H / 2,
    W * 0.3,
    W / 2,
    H / 2,
    W * 0.85,
  );
  vg.addColorStop(0, "rgba(0,0,0,0)");
  vg.addColorStop(1, "rgba(0,0,0,0.45)");
  ctx.fillStyle = vg;
  ctx.fillRect(0, 0, W, H);

  const guard = ctx.createLinearGradient(0, H * 0.55, 0, H);
  guard.addColorStop(0, "rgba(0,0,0,0)");
  guard.addColorStop(1, "rgba(0,0,0,0.6)");
  ctx.fillStyle = guard;
  ctx.fillRect(0, 0, W, H);

  addGrain(ctx, W, H, 10);
};
